export const fakeData = [
  {
    id: "4d5e6f",
    title: "CourseD",
    price: "180",
    duration: "20",
    category: "Business",
  },
  {
    id: "1a2b3c",
    title: "CourseA",
    price: "100",
    duration: "10",
    category: "Art",
  },
  {
    id: "1a2b3c",
    title: "CourseA",
    price: "100",
    duration: "10",
    category: "Art",
  },
  {
    id: "1a2b3c",
    title: "CourseA",
    price: "100",
    duration: "10",
    category: "Art",
  },
  {
    id: "1a2b3c",
    title: "CourseA",
    price: "100",
    duration: "10",
    category: "Art",
  },
  {
    id: "1a2b3c",
    title: "CourseA",
    price: "100",
    duration: "10",
    category: "Art",
  },
  {
    id: "1a2b3c",
    title: "CourseA",
    price: "100",
    duration: "10",
    category: "Art",
  },
  {
    id: "1a2b3c",
    title: "CourseA",
    price: "100",
    duration: "10",
    category: "Art",
  },
  {
    id: "1a2b3c",
    title: "CourseA",
    price: "100",
    duration: "10",
    category: "Art",
  },
  {
    id: "2b3c4d",
    title: "CourseB",
    price: "200",
    duration: "15",
    category: "Science",
  },
  {
    id: "3c4d5e",
    title: "CourseC",
    price: "150",
    duration: "12",
    category: "Technology",
  },
  {
    id: "4d5e6f",
    title: "CourseD",
    price: "180",
    duration: "20",
    category: "Business",
  },
  {
    id: "5e6f7g",
    title: "CourseE",
    price: "120",
    duration: "8",
    category: "Music",
  },
  {
    id: "6f7g8h",
    title: "CourseF",
    price: "90",
    duration: "5",
    category: "Health",
  },
  {
    id: "7g8h9i",
    title: "CourseG",
    price: "300",
    duration: "25",
    category: "Fitness",
  },
  {
    id: "8h9i0j",
    title: "CourseH",
    price: "250",
    duration: "30",
    category: "Literature",
  },
  {
    id: "9i0j1k",
    title: "CourseI",
    price: "110",
    duration: "18",
    category: "History",
  },
  {
    id: "0j1k2l",
    title: "CourseJ",
    price: "140",
    duration: "9",
    category: "Philosophy",
  },
  {
    id: "1k2l3m",
    title: "CourseK",
    price: "160",
    duration: "22",
    category: "Photography",
  },
  {
    id: "2l3m4n",
    title: "CourseL",
    price: "130",
    duration: "14",
    category: "Cooking",
  },
  {
    id: "3m4n5o",
    title: "CourseM",
    price: "170",
    duration: "16",
    category: "Design",
  },
  {
    id: "4n5o6p",
    title: "CourseN",
    price: "200",
    duration: "19",
    category: "Writing",
  },
  {
    id: "5o6p7q",
    title: "CourseO",
    price: "210",
    duration: "21",
    category: "Marketing",
  },
  {
    id: "6p7q8r",
    title: "CourseP",
    price: "220",
    duration: "23",
    category: "Business",
  },
  {
    id: "7q8r9s",
    title: "CourseQ",
    price: "230",
    duration: "27",
    category: "Tech",
  },
  {
    id: "8r9s0t",
    title: "CourseR",
    price: "240",
    duration: "28",
    category: "Finance",
  },
  {
    id: "9s0t1u",
    title: "CourseS",
    price: "250",
    duration: "24",
    category: "Economics",
  },
  {
    id: "0t1u2v",
    title: "CourseT",
    price: "260",
    duration: "26",
    category: "Management",
  },
  {
    id: "1u2v3w",
    title: "CourseU",
    price: "270",
    duration: "29",
    category: "Entrepreneurship",
  },
  {
    id: "2v3w4x",
    title: "CourseV",
    price: "280",
    duration: "31",
    category: "Leadership",
  },
  {
    id: "3w4x5y",
    title: "CourseW",
    price: "290",
    duration: "32",
    category: "Innovation",
  },
  {
    id: "4x5y6z",
    title: "CourseX",
    price: "300",
    duration: "33",
    category: "Strategy",
  },
  {
    id: "5y6z7a",
    title: "CourseY",
    price: "310",
    duration: "34",
    category: "Networking",
  },
  {
    id: "6z7a8b",
    title: "CourseZ",
    price: "320",
    duration: "35",
    category: "Consulting",
  },
  {
    id: "7a8b9c",
    title: "CourseAA",
    price: "330",
    duration: "36",
    category: "Sales",
  },
  {
    id: "8b9c0d",
    title: "CourseAB",
    price: "340",
    duration: "37",
    category: "CustomerService",
  },
  {
    id: "9c0d1e",
    title: "CourseAC",
    price: "350",
    duration: "38",
    category: "Support",
  },
  {
    id: "0d1e2f",
    title: "CourseAD",
    price: "360",
    duration: "39",
    category: "Operations",
  },
  {
    id: "1e2f3g",
    title: "CourseAE",
    price: "370",
    duration: "40",
    category: "QualityAssurance",
  },
  {
    id: "2f3g4h",
    title: "CourseAF",
    price: "380",
    duration: "41",
    category: "Training",
  },
  {
    id: "3g4h5i",
    title: "CourseAG",
    price: "390",
    duration: "42",
    category: "Compliance",
  },
  {
    id: "4h5i6j",
    title: "CourseAH",
    price: "400",
    duration: "43",
    category: "Security",
  },
  {
    id: "5i6j7k",
    title: "CourseAI",
    price: "410",
    duration: "44",
    category: "RiskManagement",
  },
  {
    id: "6j7k8l",
    title: "CourseAJ",
    price: "420",
    duration: "45",
    category: "DataAnalysis",
  },
  {
    id: "7k8l9m",
    title: "CourseAK",
    price: "430",
    duration: "46",
    category: "Cybersecurity",
  },
  {
    id: "8l9m0n",
    title: "CourseAL",
    price: "440",
    duration: "47",
    category: "ArtificialIntelligence",
  },
  {
    id: "9m0n1o",
    title: "CourseAM",
    price: "450",
    duration: "48",
    category: "MachineLearning",
  },
  {
    id: "0n1o2p",
    title: "CourseAN",
    price: "460",
    duration: "49",
    category: "Blockchain",
  },
  {
    id: "1o2p3q",
    title: "CourseAO",
    price: "470",
    duration: "50",
    category: "VirtualReality",
  },
  {
    id: "2p3q4r",
    title: "CourseAP",
    price: "480",
    duration: "51",
    category: "AugmentedReality",
  },
  {
    id: "3q4r5s",
    title: "CourseAQ",
    price: "490",
    duration: "52",
    category: "InternetofThings",
  },
  {
    id: "4r5s6t",
    title: "CourseAR",
    price: "500",
    duration: "53",
    category: "CloudComputing",
  },
  {
    id: "5s6t7u",
    title: "CourseAS",
    price: "510",
    duration: "54",
    category: "BigData",
  },
  {
    id: "6t7u8v",
    title: "CourseAT",
    price: "520",
    duration: "55",
    category: "DevOps",
  },
  {
    id: "7u8v9w",
    title: "CourseAU",
    price: "530",
    duration: "56",
    category: "MobileDevelopment",
  },
  {
    id: "8v9w0x",
    title: "CourseAV",
    price: "540",
    duration: "57",
    category: "WebDevelopment",
  },
  {
    id: "9w0x1y",
    title: "CourseAW",
    price: "550",
    duration: "58",
    category: "SoftwareEngineering",
  },
  {
    id: "0x1y2z",
    title: "CourseAX",
    price: "560",
    duration: "59",
    category: "SystemsAnalysis",
  },
  {
    id: "1y2z3a",
    title: "CourseAY",
    price: "570",
    duration: "60",
    category: "GameDevelopment",
  },
  {
    id: "2z3a4b",
    title: "CourseAZ",
    price: "580",
    duration: "61",
    category: "DigitalMarketing",
  },
];

export const categories = [
  "Health",
  "Culinary",
  "Art",
  "Technology",
  "Fitness",
  "Literature",
  "Design",
  "Business",
  "Social Science",
  "Personal Development",
  "Entrepreneurship",
  "Crafts",
  "Media",
  "Marketing",
  "Environmental Science",
  "Game Development",
  "Creativity",
  "Finance",
  "Photography",
  "Management",
];
